---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# RmarineHeatWaves

The RmarineHeatWaves R package contains a number of functions which calculate 
and display marine heat waves according to the definition of Hobday et al. (2016). 
The marine cold spell option was implemented in version 0.13 (21 Nov 2015) of the 
Python module as a result of the preparation of Schlegel et al. (submitted), wherein
the cold events are introduced and receive a brief overview.

The RmarineHeatWaves package is a translation of the original Python code written 
by Eric C. J. Oliver that can be found on [GitHub](https://github.com/ecjoliver/marineHeatWaves).

# The functions

|Function             |Description|
|---------------------|-----------|
|`detect()`           |The main function which detects the events as per the definition of Hobday et al. (2016).|
|`make_whole()`       |Constructs a continuous, uninterrupted time series of temperatures.|
|`block_average()`    |Calculates annual means for event metrics.|
|`event_line()`       |Creates a line plot of marine heat waves or cold spells.|
|`lolli_plot()`       |Creates a timeline of selected event metrics.|

The package also provides data of observed SST records for three historical MHWs: 
the 2011 Western Australia event, the 2012 Northwest Atlantic event and the 
2003 Mediterranean event.

# References

Hobday, A.J. et al. (2016), A hierarchical approach to defining marine heatwaves, Progress in Oceanography, 141, pp. 227-238, doi: 10.1016/j.pocean.2015.12.014 [pdf](http://passage.phys.ocean.dal.ca/~olivere/docs/Hobdayetal_2016_PO_HierarchMHWDefn.pdf)

Schlegel, R. W., Oliver, E. C. J., Wernberg, T. W., Smit, A. J. (submitted) Coastal and offshore co-occurrences of marine heatwaves and cold-spells. Progress in Oceanography.

# Acknowledgements

The Python code was written by Eric C. J. Oliver.

Contributors to the Marine Heatwaves definition and its numerical implementation include Alistair J. Hobday, Lisa V. Alexander, Sarah E. Perkins, Dan A. Smale, Sandra C. Straub, Jessica Benthuysen, Michael T. Burrows, Markus G. Donat, Ming Feng, Neil J. Holbrook, Pippa J. Moore, Hillary A. Scannell, Alex Sen Gupta, and Thomas Wernberg.

The translation from Python to R was done by A. J. Smit and the graphing functions were contributed to by Robert. W. Schlegel.

# Contact

A. J. Smit
Department for Biodiversity & Conservation Biology, University of the Western Cape,
Private Bag X17,  Bellville 7535, South Africa,  E-mail: ajsmit@uwc.ac.za,
Work tel.: +27 (0)21 959 3783